{{- $secretName := printf "%s-app-secret" (include "docmost.fullname" .) }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- $appSecret := "" }}

{{- if $existingSecret }}
  {{- $appSecret = index $existingSecret.data "appSecret" }}
{{- else }}
  {{- $appSecret = randAlphaNum 32 | b64enc }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  appSecret: {{ $appSecret | quote }}
