apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docmost.fullname" . }}-postgresql-secret
  labels:
    {{- include "docmost.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.auth.password | b64enc | quote }}