{{- if not .Values.docmost.smtp.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docmost.smtp.auth.secretName" . }}
type: Opaque
data:
  username: {{ .Values.docmost.smtp.auth.username | b64enc | quote }}
  password: {{ .Values.docmost.smtp.auth.password | b64enc | quote }}
{{- end }}
